Cleaned up + added support to specify files or wildcards (ie: name*.mp4)

diff --git a/mp4towebm b/mp4towebm
--- a/mp4towebm
+++ b/mp4towebm
@@ -1,12 +1,27 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-for f in *.mp4; do
+FILE_EXT=".webm"
 
-	# Get file name
-	filename=$(basename $f .mp4)
-	ext=".webm"
+[[ ! $(type -P ffmpeg) ]] && echo 'Error: The ffmpeg executable wasn not found in $PATH' && exit 1
 
-	# Convert!
-	ffmpeg -i $f -c:v libvpx -crf 4 -q:v 10 -b:v $1 -c:a libvorbis $filename$ext
+function convert_mp4(){
+    if [ $(grep -e "\.mp4" <<< "$1") ]; then
+        ffmpeg -i "$1" -c:v libvpx -crf 4 -q:v 10 -b:v $1 -c:a libvorbis "${1/\.mp4}${FILE_EXT}"
+    else
+        echo "${1} doesn't appear to be an mp4"
+    fi
+}
 
-done
+if [ -n "$1" ]; then
+    for video in "$@"; do
+        if [ -f "$video" ]; then
+            convert_mp4 "$video"
+        else
+            echo "Error: no video file(s) matching '${1}'"
+        fi
+    done
+else
+    for video in *.mp4; do
+        convert_mp4 "$video"
+    done
+fi
